/** Auto-generated Rule Engine seeds — Consolidated Developer Spec sheet 03 */
export const AUTOMATION_RULE_SEEDS = [
  {
    "ruleCode": "C0_NEW_LEAD_VALIDATE",
    "name": "Validate newly captured lead",
    "ruleType": "EVENT",
    "triggerEvent": "lead.created",
    "scope": "Organisation/Branch",
    "conditionGroup": "ALL",
    "field": "lead.mobile",
    "operator": "IS_NOT_NULL",
    "expectedValue": "true",
    "actionType": "RUN_IDENTITY_RESOLUTION",
    "actionOwnerLogic": "SYSTEM",
    "priority": "P1",
    "slaMinutes": 1,
    "escalationLogic": "Technical alert if validation fails",
    "exitCondition": "identity_check_completed = true",
    "nextStage": "C0.2",
    "status": "ACTIVE",
    "version": 1
  },
  {
    "ruleCode": "C0_WA_ACTIVE_BOT",
    "name": "Start bot for WhatsApp-active lead",
    "ruleType": "EVENT",
    "triggerEvent": "lead.contact_health_completed",
    "scope": "Organisation/Branch/Product",
    "conditionGroup": "ALL",
    "field": "lead.whatsapp_status",
    "operator": "EQUALS",
    "expectedValue": "ACTIVE",
    "actionType": "START_BOT_JOURNEY",
    "actionOwnerLogic": "BOT",
    "priority": "P2",
    "slaMinutes": 1,
    "escalationLogic": "CRM manager if message not attempted",
    "exitCondition": "bot_session_created = true",
    "nextStage": "C0.4",
    "status": "ACTIVE",
    "version": 1
  },
  {
    "ruleCode": "C0_WA_READ_NO_REPLY",
    "name": "Call WhatsApp read-no-reply lead",
    "ruleType": "TIME",
    "triggerEvent": "whatsapp.read",
    "scope": "Organisation/Branch",
    "conditionGroup": "ALL",
    "field": "communication.reply_received",
    "operator": "EQUALS",
    "expectedValue": "false",
    "actionType": "CREATE_CALL_TASK",
    "actionOwnerLogic": "AUTODIALER_QUEUE",
    "priority": "P2",
    "slaMinutes": 15,
    "escalationLogic": "Telesales manager; reassign after 15 min",
    "exitCondition": "call_disposition IS NOT NULL",
    "nextStage": "C0.5",
    "status": "ACTIVE",
    "version": 1
  },
  {
    "ruleCode": "C0_HOT_CALLBACK",
    "name": "Call explicit callback request",
    "ruleType": "EVENT",
    "triggerEvent": "customer.callback_requested",
    "scope": "Organisation/Branch",
    "conditionGroup": "ALL",
    "field": "lead.priority",
    "operator": "IN",
    "expectedValue": "HOT,CRITICAL",
    "actionType": "CREATE_CALL_TASK",
    "actionOwnerLogic": "SALES_EXECUTIVE",
    "priority": "P1",
    "slaMinutes": 5,
    "escalationLogic": "Team leader at 5 min; reassign at 10 min",
    "exitCondition": "call_connected OR valid_disposition",
    "nextStage": "C0.6",
    "status": "ACTIVE",
    "version": 1
  },
  {
    "ruleCode": "C0_QUOTE_READY",
    "name": "Validate quote readiness",
    "ruleType": "STAGE",
    "triggerEvent": "lead.qualification_completed",
    "scope": "Organisation/Product",
    "conditionGroup": "ALL",
    "field": "qualification.mandatory_fields_complete",
    "operator": "EQUALS",
    "expectedValue": "true",
    "actionType": "CREATE_QUOTATION_TASK",
    "actionOwnerLogic": "CURRENT_SALES_OWNER",
    "priority": "P1",
    "slaMinutes": 60,
    "escalationLogic": "Sales manager if overdue",
    "exitCondition": "quotation_created = true",
    "nextStage": "C1.1",
    "status": "ACTIVE",
    "version": 1
  },
  {
    "ruleCode": "C1_QUOTE_FOLLOWUP",
    "name": "Follow up shared quotation",
    "ruleType": "TIME",
    "triggerEvent": "quote.shared",
    "scope": "Organisation/Branch",
    "conditionGroup": "ALL",
    "field": "quote.acknowledged",
    "operator": "EQUALS",
    "expectedValue": "false",
    "actionType": "CREATE_FOLLOWUP_TASK",
    "actionOwnerLogic": "CURRENT_SALES_OWNER",
    "priority": "P2",
    "slaMinutes": 120,
    "escalationLogic": "Team leader at SLA",
    "exitCondition": "quote_acknowledged OR objection_captured",
    "nextStage": "C1.2",
    "status": "ACTIVE",
    "version": 1
  },
  {
    "ruleCode": "C1_TEST_DRIVE",
    "name": "Create test drive task",
    "ruleType": "EVENT",
    "triggerEvent": "test_drive.requested",
    "scope": "Organisation/Branch/Product",
    "conditionGroup": "ALL",
    "field": "lead.status",
    "operator": "EQUALS",
    "expectedValue": "OPEN",
    "actionType": "SCHEDULE_TEST_DRIVE",
    "actionOwnerLogic": "CURRENT_SALES_OWNER",
    "priority": "P1",
    "slaMinutes": 240,
    "escalationLogic": "Sales manager if not scheduled same day",
    "exitCondition": "test_drive_scheduled = true",
    "nextStage": "C1.7",
    "status": "ACTIVE",
    "version": 1
  },
  {
    "ruleCode": "C1_MANAGER_INTERVENTION",
    "name": "Escalate stuck hot lead",
    "ruleType": "TIME",
    "triggerEvent": "lead.stage_unchanged",
    "scope": "Organisation/Branch",
    "conditionGroup": "ALL",
    "field": "lead.priority",
    "operator": "IN",
    "expectedValue": "HOT,CRITICAL",
    "actionType": "CREATE_MANAGER_INTERVENTION",
    "actionOwnerLogic": "SALES_MANAGER",
    "priority": "P1",
    "slaMinutes": 30,
    "escalationLogic": "Branch head after 30 min",
    "exitCondition": "manager_action_recorded = true",
    "nextStage": "C1.8",
    "status": "ACTIVE",
    "version": 1
  },
  {
    "ruleCode": "C1A_DOC_PENDING",
    "name": "Escalate pending finance documents",
    "ruleType": "TIME",
    "triggerEvent": "finance.application_created",
    "scope": "Organisation/Finance Partner",
    "conditionGroup": "ALL",
    "field": "finance.documents_complete",
    "operator": "EQUALS",
    "expectedValue": "false",
    "actionType": "CREATE_DOCUMENT_COLLECTION_TASK",
    "actionOwnerLogic": "FINANCE_EXECUTIVE",
    "priority": "P2",
    "slaMinutes": 2880,
    "escalationLogic": "Finance manager at 48 hours",
    "exitCondition": "finance.documents_complete = true",
    "nextStage": "C1A.2",
    "status": "ACTIVE",
    "version": 1
  },
  {
    "ruleCode": "C1A_FINANCE_REJECTED",
    "name": "Route rejected finance case",
    "ruleType": "EVENT",
    "triggerEvent": "finance.rejected",
    "scope": "Organisation/Branch",
    "conditionGroup": "ANY",
    "field": "finance.alternate_lender_available",
    "operator": "EQUALS",
    "expectedValue": "true",
    "actionType": "CREATE_ALTERNATE_FINANCE_TASK",
    "actionOwnerLogic": "FINANCE_TEAM",
    "priority": "P1",
    "slaMinutes": 240,
    "escalationLogic": "Finance manager if no alternate decision",
    "exitCondition": "alternate_finance_started OR nurture_selected",
    "nextStage": "C1A.1",
    "status": "ACTIVE",
    "version": 1
  },
  {
    "ruleCode": "C2_BOOKING_RECEIVED",
    "name": "Create vehicle allocation action",
    "ruleType": "EVENT",
    "triggerEvent": "booking.payment_received",
    "scope": "Organisation/Branch/Product",
    "conditionGroup": "ALL",
    "field": "booking.status",
    "operator": "EQUALS",
    "expectedValue": "CONFIRMED",
    "actionType": "ALLOCATE_VEHICLE",
    "actionOwnerLogic": "STOCK_MANAGER",
    "priority": "P1",
    "slaMinutes": 240,
    "escalationLogic": "Sales manager if stock not allocated",
    "exitCondition": "vehicle_allocation_id IS NOT NULL",
    "nextStage": "C2.2",
    "status": "ACTIVE",
    "version": 1
  },
  {
    "ruleCode": "C2_PDI_COMPLETE",
    "name": "Move vehicle to delivery readiness",
    "ruleType": "EVENT",
    "triggerEvent": "pdi.approved",
    "scope": "Organisation/Branch",
    "conditionGroup": "ALL",
    "field": "pdi.status",
    "operator": "EQUALS",
    "expectedValue": "APPROVED",
    "actionType": "CREATE_DELIVERY_READINESS_TASK",
    "actionOwnerLogic": "DELIVERY_TEAM",
    "priority": "P1",
    "slaMinutes": 240,
    "escalationLogic": "Delivery manager if overdue",
    "exitCondition": "vehicle_ready = true",
    "nextStage": "C3.1",
    "status": "ACTIVE",
    "version": 1
  },
  {
    "ruleCode": "C3_DELIVERY_DONE",
    "name": "Activate lifecycle",
    "ruleType": "EVENT",
    "triggerEvent": "delivery.done",
    "scope": "Organisation/Branch",
    "conditionGroup": "ALL",
    "field": "delivery.proof_complete",
    "operator": "EQUALS",
    "expectedValue": "true",
    "actionType": "ACTIVATE_LIFECYCLE",
    "actionOwnerLogic": "SYSTEM",
    "priority": "P2",
    "slaMinutes": 1,
    "escalationLogic": "Technical alert if lifecycle not created",
    "exitCondition": "lifecycle_record_created = true",
    "nextStage": "LIFECYCLE",
    "status": "ACTIVE",
    "version": 1
  },
  {
    "ruleCode": "LIFECYCLE_SERVICE_DUE",
    "name": "Create service reminder action",
    "ruleType": "TIME",
    "triggerEvent": "service.due",
    "scope": "Organisation/Branch",
    "conditionGroup": "ALL",
    "field": "customer_vehicle.status",
    "operator": "EQUALS",
    "expectedValue": "ACTIVE",
    "actionType": "SEND_SERVICE_REMINDER",
    "actionOwnerLogic": "CRM_OR_SERVICE_TEAM",
    "priority": "P3",
    "slaMinutes": 1440,
    "escalationLogic": "Service manager for missed first service",
    "exitCondition": "reminder_sent OR service_booking_created",
    "nextStage": "L1",
    "status": "ACTIVE",
    "version": 1
  }
];

export const getActiveAutomationRules = () => AUTOMATION_RULE_SEEDS.filter((r) => r.status === 'ACTIVE');

export const getAutomationRule = (code) => AUTOMATION_RULE_SEEDS.find((r) => r.ruleCode === code);
